//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Akash_Ade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubMember
    {
        public System.Guid Id { get; set; }
        public string MemberName { get; set; }
        public System.Guid SocietyId { get; set; }
        public int Gender { get; set; }
        public int MembershipCategory { get; set; }
        public System.Guid HobbiesId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual Hobby Hobby { get; set; }
        public virtual Society Society { get; set; }
    }
}
